#!/usr/bin/env perl
# LICENSE:
#   Copyright (C) 2003-2021 Opsview Limited. All rights reserved
#
#   This file is part of Opsview
#

# SYNTAX:
my $usage = qq{
   notify_by_summitai
   Copyright (C) 2003-2021 Opsview Limited. All rights reserved

Usage: notify_by_summitai [-h] [-n] [-d] [-m]

Where:
  -h - this help text
  -n - do not send acknowledgements
  -d - debug mode, prints errors to stderr and syslog
  -m - message to send, will override the Opsview notification data if specified
};

use strict;
use warnings;
use lib qw( /opt/opsview/monitoringscripts/lib /opt/opsview/perl/lib/perl5 );

use Data::Dump qw( pp );
use DBI;
use Fcntl ':flock';
use Getopt::Long;
use JSON;
use Opsview::Config::Notifications;
use REST::Client;
use Sys::Syslog;
use YAML::Tiny;
use Log::Log4perl;

openlog("notify_by_summitai", "ndelay,pid", "local6");

Log::Log4perl::init(\<<'CONFIG');
  log4perl.rootLogger = DEBUG, Screen, File

  log4perl.appender.Screen = Log::Log4perl::Appender::Screen
  log4perl.appender.Screen.layout = SimpleLayout

  log4perl.appender.File = Log::Log4perl::Appender::File
  log4perl.appender.File.filename = notify_by_summit.log
  log4perl.appender.File.layout = PatternLayout
  log4perl.appender.File.layout.ConversionPattern = [%d] [%p] %m%n
CONFIG

my $logger = Log::Log4perl->get_logger();

my ( $help_mode, $debug_mode, $no_ack );
$debug_mode = $no_ack = $help_mode = 0;

GetOptions(
    'h'   => \$help_mode,
    'd'   => \$debug_mode,
    'n'   => \$no_ack,
);

$debug_mode = 1;

            
my $db_dir  = '/opt/opsview/monitoringscripts/var/notifications/notify_by_summitai/';
my $db_nane = 'incidents_debug.db';
my $db_path = $db_dir . $db_nane;

my $dbsn = "DBI:SQLite:uri=file:$db_path";
my $dbh = DBI->connect( $dbsn . "?mode=rwc", '', '', { RaiseError => 1 } );

db_init( $dbh );

my $config_path = '/opt/opsview/monitoringscripts/etc/notifications/notify_by_summitai_debug.yaml';
my $config = YAML::Tiny->read( $config_path );

my $client = REST::Client->new();
$client->setHost( $config->[0]->{summitai}->{connection}->{server} );
$client->addHeader( 'Content-Type', 'application/json' );

my %ai_data = (
    'ServiceName' => 'IM_LogOrUpdateIncident',
    'objCommonParameters' => {
        '_ProxyDetails' => {
            'AuthType' => 'APIKEY',
            'APIKey' => $config->[0]->{summitai}->{connection}->{apikey},
            'ProxyID' => 0,
            'ReturnType' => 'JSON',
            'OrgID' => 1
        },
        'RequestType' => 'RemoteCall'
    }
);

my $rest_endpoint = $config->[0]->{summitai}->{endpoints}->{api};

my $name = $config->[0]->{summitai}->{fields}->{name};
my $open_ticket_status = $config->[0]->{summitai}->{fields}->{status}->{open}->{ticket_status};
my $closed_ticket_status = $config->[0]->{summitai}->{fields}->{status}->{closed}->{ticket_status};

my $socket = '/opt/opsview/var/results.sock';

my $env_vars = env_setup();

my @db_id = db_search( $dbh, $env_vars );

if ( $debug_mode ) {
    syslog('LOG_DEBUG', "DB Search: " . pp(@db_id));
}


if ( $env_vars->{'NAGIOS_NOTIFICATIONTYPE'} eq 'RECOVERY' ) {
    print $db_id[0];
    $logger->info('Processing recovery notification');
    if ( $db_id[0] ) {
	$logger->info('DB ID:' $db_id[0])
        syslog('LOG_DEBUG', "Recovery: " . pp(@db_id));
        incident_close( $client, $rest_endpoint, $db_id[0]{TICKET} );
        db_archive( $dbh, $db_id[0] );
    }
} 
else {
    my $ticket_id;
    if ( $db_id[0] ) {
        my $ticket_data = incident_search($client, $db_id[0]{TICKET});
        if ( $ticket_data ) {
            if ( $ticket_data->{TicketStatus} ne 'Closed' || $ticket_data->{TicketStatus} ne 'Cancelled' || $ticket_data->{TicketStatus} ne 'Closed' || $ticket_data->{TicketStatus} ne 'Resolved' ) {
                if ( ! $db_id[0]{ACK} ) {
                    my $logging_id = $ticket_data->{TicketIdentifier};
		    $logger->info('Sending ack for: ' $logging_id);
                    send_ack($socket, $env_vars, $ticket_data->{TicketIdentifier}, $debug_mode);
                    db_ack($dbh, $db_id[0]{TICKET});
                }
            }
            else {
                db_archive( $dbh, $db_id[0] );
                $ticket_id = incident_create( $client, $env_vars, $rest_endpoint, $config, %ai_data );
                $logger->info('Created ticket: ' $ticket_id);
		syslog('LOG_DEBUG', "Ticket ID: $ticket_id");
                if ( $ticket_id ) {
                    db_insert( $dbh, $env_vars, $ticket_id );
                    send_ack($socket, $env_vars, $ticket_id, $debug_mode);
                    db_ack($dbh, $db_id[0]{TICKET});
                }
            }
        }
        else {
            db_archive( $dbh, $db_id[0] );
            $ticket_id = incident_create( $client, $env_vars, $rest_endpoint, $config, %ai_data );
            syslog('LOG_DEBUG', "Ticket ID: $ticket_id");
            if ( $ticket_id ) {
                db_insert( $dbh, $env_vars, $ticket_id );
		$logger->info('Archiving: ' $ticket_id);
                send_ack($socket, $env_vars, $ticket_id, $debug_mode);
                db_ack($dbh, $db_id[0]{TICKET});
            }
        }
    } 
    else {
        $ticket_id = incident_create( $client, $env_vars, $config );
        syslog('LOG_DEBUG', "Ticket ID: $ticket_id");
	$logger->info('Created ticket: ' $ticket_id);
        if ( $ticket_id ) {
            db_insert( $dbh, $env_vars, $ticket_id );
            send_ack($socket, $env_vars, $ticket_id, $debug_mode);
            db_ack($dbh, $ticket_id);
        }
    }
}

sub db_init {
    my ($dbh) = @_;

    my $create_db = qq {
        CREATE TABLE IF NOT EXISTS tickets (
            ID          INTEGER PRIMARY KEY AUTOINCREMENT,
            DT          DATETIME DEFAULT CURRENT_TIMESTAMP,
            HOSTNAME    TEXT NOT NULL,
            SERVICE     TEXT,
            LASTOK      DATETIME DEFAULT CURRENT_TIMESTAMP,
            TICKET      CHAR(50),
            ACK         INT
        );
    };
  
    my $ret = $dbh->do($create_db);
    if ( $ret < 0 ) {
        print "Cannot run SQL $create_db: $DBI::errstr\n";
        return;
    }

    my $create_db_archive = qq {
        CREATE TABLE IF NOT EXISTS tickets_archive (
            ID          INTEGER PRIMARY KEY AUTOINCREMENT,
            DT          DATETIME DEFAULT CURRENT_TIMESTAMP,
            HOSTNAME    TEXT NOT NULL,
            SERVICE     TEXT,
            LASTOK      DATETIME DEFAULT CURRENT_TIMESTAMP,
            TICKET      CHAR(50),
            ACK         INT
        );
    };

    $ret = $dbh->do($create_db_archive);
    if ( $ret < 0 ) {
        print "Cannot run SQL $create_db_archive: $DBI::errstr\n";
        exit 3;
    }
}

sub env_setup {
    my $vars;
    my @env = (
        'NAGIOS_HOSTNAME', 
        'NAGIOS_HOSTGROUPNAME', 
        'NAGIOS_HOSTADDRESS', 
        'NAGIOS_HOSTSTATE', 
        'NAGIOS_HOSTSTATETYPE', 
        'NAGIOS_HOSTOUTPUT', 
        'NAGIOS_LASTHOSTCHECK', 
        'NAGIOS_LASTHOSTUP', 
        'NAGIOS_SERVICENOTES', 
        'NAGIOS_SERVICEDESC', 
        'NAGIOS_SERVICESTATE', 
        'NAGIOS_SERVICEOUTPUT', 
        'NAGIOS_SERVICESTATETYPE', 
        'NAGIOS_LASTSERVICECHECK', 
        'NAGIOS_LASTSERVICEOK',
        'NAGIOS_NOTIFICATIONTYPE',
        'OPSVIEW_KEYWORDS',
        'NAGIOS_LONGSERVICEOUTPUT'
    );

    for ( @env ) {
        $vars->{$_} = $ENV{$_};
    }
    if ($debug_mode) {
        syslog('LOG_DEBUG', "VARIABLES: " . pp($vars) );
    }
    syslog('LOG_DEBUG', "VARIABLES: " . pp($vars) );
    return $vars;
}

sub db_ack {
    my ( $dbh, $ticket_id ) = @_;

    $dbh->do(
        qq{ UPDATE tickets SET ACK = 1 WHERE TICKET = ? },
        {},
        $ticket_id,
    );
}

sub db_archive {
    my ( $dbh, $db_id ) = @_;

    my $sth = $dbh->prepare( "INSERT INTO tickets_archive (DT, HOSTNAME, SERVICE, LASTOK, TICKET, ACK) SELECT DT, HOSTNAME, SERVICE, LASTOK, TICKET, ACK FROM tickets WHERE ID = ?" );

    $sth->execute( $db_id[0]{ID} );

    $dbh->do( qq{DELETE FROM tickets WHERE ID = ?}, {}, $db_id[0]{ID} );

    $logger->info('DB Archived:' $db_id[0]{ID});
}

sub db_insert {
    my ( $dbh, $env_vars, $ticket_id ) = @_;

    $dbh->do( 
        qq{ INSERT INTO tickets 
        (DT, HOSTNAME, SERVICE, LASTOK, TICKET, ACK)
        VALUES (?,?,?,?,?,?); }, 
        {},
        time(),
        $env_vars->{'NAGIOS_HOSTNAME'},
        $env_vars->{'NAGIOS_SERVICEDESC'} || 'NULL',
        $env_vars->{'NAGIOS_LASTSERVICEOK'} || $env_vars->{'NAGIOS_LASTHOSTUP'},
        $ticket_id,
        0
    );
    $logger->info('DB Insert:' $ticket_id);

}

sub db_search {
    my ( $dbh, $env_vars ) = @_;

    my $sth = $dbh->prepare( "SELECT * FROM tickets WHERE HOSTNAME = ? AND SERVICE = ?" );

    if ( $env_vars->{'NAGIOS_SERVICEDESC'} ) {
        $sth->execute( $env_vars->{'NAGIOS_HOSTNAME'}, $env_vars->{'NAGIOS_SERVICEDESC'} );
    }
    else {
        $sth->execute( $env_vars->{'NAGIOS_HOSTNAME'}, 'NULL' );
    }
    my $row = $sth->fetchrow_hashref;

    syslog('LOG_DEBUG', pp($row) );
    $logger->info('DB Searched:' $row);

    return $row;
}

sub incident_close {
    my ( $client, $db_ticket_id, $ticketno ) = @_;
    my ( $description );

    if ( $env_vars->{'NAGIOS_SERVICEDESC'} ) {
        $description = '[' . $env_vars->{'NAGIOS_HOSTNAME'} . '] ' . $env_vars->{'NAGIOS_SERVICEDESC'} . ' is ' . $env_vars->{'NAGIOS_SERVICESTATE'};
    }
    else {
        $description = '[' . $env_vars->{'NAGIOS_HOSTNAME'} . '] Host status is ' . $env_vars->{'NAGIOS_HOSTSTATE'};

    }

    if ( $debug_mode ) {
        print "### INCIDENT CLOSE ###\n";
    }

    $ticketno = $db_id[0]{TICKET};
    
    $logger->info('Incitent Close Begin');
    $logger->info('Incitent Close' $ticketno $description);

    my $engineer = $config->[0]->{summitai}->{email};
    $logger->info('Incitent Close' $ticketno $description);

    my $ticket_data = incident_search($client, $db_id[0]{TICKET});
    $logger->info('Incitent Close' $ticketno $description);

    my $ticket_engineer = $ticket_data->{Assigned_Engineer_Email};

    if ( $ticket_engineer ) {
    $engineer = $ticket_engineer;
    }
    else {
    $engineer = $config->[0]->{summitai}->{email};
    }
    $logger->info('Incitent Close' $ticketno $description);


    my %update_data = (
        'IncidentContainerJsonObj' => {
            "Updater" => "Executive",
            "Ticket" => {
                "Ticket_No" => $ticketno,
                "IsFromWebService" => "true",
                "Assigned_Engineer_Email" => $engineer,
                "Status" => "In-Progress",
                "PageName" => "TicketDetail",
                "OpenCategory_Name" => "",
                "Source" => "",
            },
            "TicketInformation" => {
                "Solution" => $description
            },
            "CustomFields" => []
        }
    );


    my %close_data = (
        'IncidentContainerJsonObj' => {
            "Updater" => "Executive",
            "Ticket" => {
                "Ticket_No" => $ticketno,
                "IsFromWebService" => "true",
                "Assigned_Engineer_Email" => $engineer,
                "Status" => "Resolved",
                "OpenCategory_Name" => "",
                "Source" => "",
                "PageName" => "TicketDetail",
                "ResolutionCodeName" => "Auto-Closed by System",
                "Closure_Code_Name" => "Auto-Closed by System",
                "Response_SLA_Reason" => "Auto-Closed by Opsview",
                "Resolution_SLA_Reason" => "Auto-Closed by Opsview",
            },
            "TicketInformation" => {
                "Solution" => $description
            },
             "CustomFields" => []
        }
    );

    $ai_data{'objCommonParameters'}{'incidentParamsJSON'} = \%update_data; 
    $logger->info("UPDATE BODY: " . encode_json( \%ai_data ));
    syslog('LOG_DEBUG', "UPDATE BODY: " . encode_json( \%ai_data ) );

    $client->POST( $rest_endpoint, encode_json( \%ai_data ) );
    syslog('LOG_DEBUG', "UPDATE POST: " . pp ($client) ); 
    $logger->info("UPDATE POST: " . pp ($client));
    my $update_response = $client->responseContent();
    syslog('LOG_DEBUG', "UPDATE RESPONSE: " . encode_json( $update_response ) );
    $logger->info("UPDATE RESPONSE: "  . encode_json( $update_response ) );

    my $json = JSON->new->allow_nonref;
    my $json_result;
    eval { $json_result = $json->decode($update_response); };

    my $update_message = $json_result->{Message};
    $logger->info("UPDATE RESPONSE MESSAGE: " $update_message);

    if ($update_message eq "Ticket details are updated successfully") {

        $ai_data{'objCommonParameters'}{'incidentParamsJSON'} = \%close_data;
        syslog('LOG_DEBUG', "CLOSE BODY: " . encode_json( \%ai_data ) );
	$logger->info("CLOSE BODY: " . encode_json( \%ai_data ));

        $client->POST( $rest_endpoint, encode_json( \%ai_data ) );
        syslog('LOG_DEBUG', "CLOSE POST: " . pp ($client) ); 
        $logger->info("CLOSE POST: " . pp ($client));

        my $close_response = $client->responseContent();
        syslog('LOG_DEBUG', "CLOSE RESPONSE: " . encode_json( $close_response ) );
        $logger->info("CLOSE RESPONSE: "  . encode_json( $close_response ) );

        print pp( $close_response ) . "\n";
        $logger->info("CLOSE RESPONSE: "  . pp( $close_response ) );

        }

    if ($@) {
        print pp($@);
        print pp("Fatal: unable to decode response from server: $@");
        syslog('LOG_DEBUG', "[incident_close] Fatal: unable to decode response from server: $@" );
        exit 3;
    }

    if ( $debug_mode ) {
        print pp($json_result);
	$logger->info("RESULT: "  . pp($json_result));
    }
}

sub incident_create {
    my ( $client, $env_vars, $config ) = @_;
    my ( $description, $message, $priority, $severity, $urgency, $affected_service, $cat );

    if ( $debug_mode ) {
        print "### INCIDENT CREATE ###\n";
    }
    $logger->info('Incitent Create Begin');

    if ( $env_vars->{'NAGIOS_SERVICEDESC'} ) {
        $description = '[' . $env_vars->{'NAGIOS_HOSTNAME'} . '] ' . $env_vars->{'NAGIOS_SERVICEDESC'} . ' is ' . $env_vars->{'NAGIOS_SERVICESTATE'};
        if ( $env_vars->{'NAGIOS_LONGSERVICEOUTPUT'} ) {
            $message = $env_vars->{'NAGIOS_SERVICEOUTPUT'} . $env_vars->{'NAGIOS_LONGSERVICEOUTPUT'};
        }
        else {
            $message = $env_vars->{'NAGIOS_SERVICEOUTPUT'};
        }
        $priority = $config->[0]->{summitai}->{priority}->{$env_vars->{'NAGIOS_SERVICESTATE'}};
        $severity = $config->[0]->{summitai}->{severity}->{$env_vars->{'NAGIOS_SERVICESTATE'}};
        $urgency = $config->[0]->{summitai}->{urgency}->{$env_vars->{'NAGIOS_SERVICESTATE'}};
    } 
    else {
        $description = '[' . $env_vars->{'NAGIOS_HOSTNAME'} . '] HOST status is ' . $env_vars->{'NAGIOS_HOSTSTATE'};
        $message = $env_vars->{'NAGIOS_HOSTOUTPUT'};
        $priority = $config->[0]->{summitai}->{priority}->{$env_vars->{'NAGIOS_HOSTSTATE'}};
        $severity = $config->[0]->{summitai}->{severity}->{$env_vars->{'NAGIOS_HOSTSTATE'}};
        $urgency = $config->[0]->{summitai}->{urgency}->{$env_vars->{'NAGIOS_HOSTSTATE'}};

    }


    if ( $env_vars->{'NAGIOS_SERVICEDESC'} ) {
        if ($env_vars->{'NAGIOS_SERVICEDESC'} =~ m/_Cisco/) {
             $cat = "114";
         }
         elsif ($env_vars->{'NAGIOS_SERVICEDESC'} =~ m/_Citrix/) {
             $cat = "229";
         }
         elsif ($env_vars->{'NAGIOS_SERVICEDESC'} =~ m/_Hyper-V/) {
             $cat = "47";
         }
         elsif ($env_vars->{'NAGIOS_SERVICEDESC'} =~ m/_Connectivity/) {
             $cat = "114";
         }
         elsif ($env_vars->{'NAGIOS_SERVICEDESC'} =~ m/_Dell PowerMax/) {
             $cat = "149";
         }
         elsif ($env_vars->{'NAGIOS_SERVICEDESC'} =~ m/_Horizon/) {
             $cat = "233";
         }
         elsif ($env_vars->{'NAGIOS_SERVICEDESC'} =~ m/_HP3PAR/) {
             $cat = "149";
         }
         elsif ($env_vars->{'NAGIOS_SERVICEDESC'} =~ m/_HTTPS/) {
             $cat = "47";
         }
         elsif ($env_vars->{'NAGIOS_SERVICEDESC'} =~ m/_Netscaler/) {
             $cat = "229";
         }
         elsif ($env_vars->{'NAGIOS_SERVICEDESC'} =~ m/_Telnet/) {
             $cat = "47";
         }
         elsif ($env_vars->{'NAGIOS_SERVICEDESC'} =~ m/_Vsphere/) {
             $cat = "47";
         }
         elsif ($env_vars->{'NAGIOS_SERVICEDESC'} =~ m/_Windows/) {
             $cat = "47";
         }
         elsif ($env_vars->{'NAGIOS_SERVICEDESC'} =~ m/_Zerto/) {
             $cat = "231";
         }
         elsif ($env_vars->{'NAGIOS_SERVICEDESC'} =~ m/_Dell PowerStore/) {
             $cat = "149";
         }
         elsif ($env_vars->{'NAGIOS_SERVICEDESC'} =~ m/_IBM FlashStorage/) {
             $cat = "149";
         }
         elsif ($env_vars->{'NAGIOS_SERVICEDESC'} =~ m/_Cloudian/) {
             $cat = "149";
         }
         else {
             $cat = "47"
         }
    }
    else {
        $cat = "47"
    }

#    if ( $config->[0]->{summitai}->{fields}->{affected_service}->{$env_vars->{'NAGIOS_HOSTGROUPNAME'}} ) { 
#        $affected_service = $config->[0]->{summitai}->{fields}->{affected_service}->{$env_vars->{'NAGIOS_HOSTGROUPNAME'}};
#    }
#    else {
#        $affected_service = $env_vars->{'NAGIOS_HOSTGROUPNAME'};
#    }

    $message =~ s/\|.*//;
    $message=substr($message,0,9999);

    my %incident_data = (
        'IncidentContainerJsonObj' => {
            "Updater" => "Caller",
            "Ticket" => {
                "IsFromWebService" => "true",
                "Classification_Name" => "Opsview Event",
                "Sup_Function" => "MSCW",
                "Caller_EmailID" => $config->[0]->{summitai}->{email},
                "Status" => "New",
                "Source" => "Opsview",
                "Priority_Name" => $priority,
                "Urgency_Name" => $urgency,
                "Assigned_WorkGroup_Name" => "Service Desk (Alarms)",
                "Medium" => "Application",
                "Impact_Name" => $severity,
                "Category" => $cat,
                "OpenCategory" => $cat,
                "SLA_Name" => "24X7",
                "Description" => $description,
                "PageName" => "LogTicket"
            },
            "TicketInformation" => {
                "Information" => $message,
            },
             "CustomFields" => [
                 {
                 "GroupName" => "Incident Additional Information",
                 "Name" => "Affected Service",
            }
            ],
        }
    );

    $ai_data{'objCommonParameters'}{'incidentParamsJSON'} = \%incident_data;

    syslog('LOG_DEBUG', "POST JSON: " . pp( encode_json( \%ai_data ) ) );
    $logger->info("Create incident json: " . pp( %ai_data  ));

    if ( $debug_mode ) {
        syslog('LOG_DEBUG', "POST JSON: " . pp( %ai_data ) );
    }

    $client->POST( $rest_endpoint, encode_json( \%ai_data ) );
    print pp(\%ai_data);
    my $create_response = $client->responseContent();

    syslog('LOG_DEBUG', "Response: " . pp( $create_response ) );
    $logger->info("Create incident response: " $create_response);
    print pp($create_response);
    my $json = JSON->new->allow_nonref;
    my $json_result;
    eval { $json_result = $json->decode($create_response); };

    my $ticketno = $json_result->{TicketNo};
    $logger->info("Created ticket: " $ticketno);
    print pp("Opened ticket: $ticketno");

    if ($@) {
        syslog('LOG_WARNING', "[incident_create] Fatal: unable to decode response from server: $@" );
        exit 3;
    }

    if ( $debug_mode ) {
        syslog('LOG_DEBUG', "POST JSON:" . pp( $json_result ) );
    }

    return $ticketno;
}

sub incident_search {
    my ( $client, $db_ticket_id ) = @_;

    my %ai_search = (
        'ServiceName' => 'IM_GetIncidentDetailsAndChangeHistory',
        'objCommonParameters' => {
            '_ProxyDetails' => {
                'AuthType' => 'APIKEY',
                'APIKey' => $config->[0]->{summitai}->{connection}->{apikey},
                'ProxyID' => 0,
                'ReturnType' => 'JSON',
                'OrgID' => 1
            },
            'RequestType' => 'RemoteCall',
            'TicketNo' => $db_ticket_id
        }
    );

    $client->POST( $rest_endpoint, encode_json( \%ai_search ) );
    syslog('LOG_DEBUG', "SEARCH POST: " . pp ($client) );
    my $search_response = $client->responseContent();
    syslog('LOG_DEBUG', "SEARCH RESPONSE: " . encode_json( $search_response ) );
    my $json = JSON->new->allow_nonref;
    my $json_result;
    eval { $json_result = $json->decode($search_response); };
    if ($@) {
        if ( $search_response =~ /Failed to retrieve Ticket/ ) {
            return 0;
        }
        else {
            syslog('LOG_WARNING', "[incident_search] Fatal: unable to decode response from server: $search_response" );
            exit 3;
        }
    }

    if ( $debug_mode ) {
        print pp($json_result);
    }

    if ( $json_result->{OutputObject} ) {
        return $json_result->{OutputObject}->{IncidentDetails}->{TicketDetails}->[0];
    }
    else {
        return undef;
    }
}


sub send_ack {
    my ( $socket, $env_vars, $ticket_id, $debug_mode ) = @_;
    my ($string, $description);

    my $message = "Ticket ID: $ticket_id";

    if ( $env_vars->{'NAGIOS_SERVICEDESC'} ) {
        $string = join(';', '[' . time . '] ACKNOWLEDGE_SVC_PROBLEM'
            , $env_vars->{'NAGIOS_HOSTNAME'}
            , $env_vars->{'NAGIOS_SERVICEDESC'}
            , 1
            , 1
            , 0
            , 'notify_by_summitai'
            , $message
        );
    } 
    else {
        $string = join(';', '[' . time . '] ACKNOWLEDGE_HOST_PROBLEM'
            , $env_vars->{'NAGIOS_HOSTNAME'}
            , 1
            , 1
            , 0
            , 'notify_by_summitai'
            , $message
        );
    }
    if ( $debug_mode ) {
      print "ACKNOWLEDGEMENT: $string\n";
      syslog('LOG_DEBUG', "ACKNOWLEDGEMENT: $string");
    }
    open(my $fh, '>>', $socket);
    flock($fh, LOCK_EX) or die "Could not lock '$socket' - $!";
    print {$fh} "$string\n";
    close($fh);
}
